language: go

go:
- tip

script:
- make build

deploy:
  provider: releases
  api_key:
    secure: "tANJ68SVi3RmhpLoYsSm4504WncKvB3kKQ880NP0mVZME3P64ecAgwmcCjs5MUtAbrs1tHB+G1rzimRpuSusP2BvJI3C5tWNg94VBstT6SRhb+D3FmbZ4NKjYU18hDC0Hps9kUNRci9xUg4A4s7oe+ZjxirWXqCpzHMFf/+goLwd0fm1p3fm06CiPtmXj3VMWdDLxCer30zyRTdqy8cOHbthbfDKLKxrYoig7KSVUaokUxj6VGv1AALQj/YGh+tqCVsRIWv3OmRYPg9MGb57VyOfUFPOZ3xnY0CdOgROyrORtP7hebHSA0iiF4NSM8mnJS9NHLLeX4MyEb4N5kutI+RnlbjXnoUbcV+2+T2Q3J5GjgULPF0+8XHcKcW4PzwDUIqm1QsXb0Rn7zDe/ztxWipLDiwzzSpO/WVRLDbNaKClM2EQQ0S7BJEsSh17u8W5H4hYVHP4aFpV4R8VJ9j84+tr/BK5K8F69Rh0a4jNQ9Ar5kquqePYTAF8NJ6/3DprXv7e8P3loiUo4GRLkuS9nxRcYW32gsfwbeQnm1OGX3A0hvcKsS1kjtfWu/Ltv1ywPc0hoFTpEVxdwpc61W+B3VmPugyBW7f+gjv0ESV4MHsWUsLgK3NX7wyRYqMRD2cqqfnyb9aiMqo/lEvPhJsv2rsYstBwdSkAiGm8Sb/h1S8="
  file: "whats-my-ip"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
