language: go

go:
  - tip

script:
  - make build

deploy:
  provider: releases
  api_key:
    secure: "nvO1leXfDfQgmq6eA75dWkz+PXN/r/eRl1cAVKziiaNC7vA4BK4KmdV2/WgZ2Z4rDTA7b2PPqhQUcYy/9NMdCrHwtjNhcFFpiI0R/SugqS+ApRR1CYtcurIKCRRIPOgyVo/Lg9k/soSmfGf9NUU2Xc/af2rYqZavjbJLbB3coD/DFp8chB75m3krsxLBGhxursHCBuzkcgasI4QY0GaTKYDQ+I8dixDH8tLrKdBS/OVbKdakHN2Ie+DTCGRcXc0Msd9EAGD9Ul/XuzYzajmxoF3mbVJ/XO+kOv1GzMfgsSmW7wxLkRLEfVs75ut4F5u/il4xSFbn1lc2UATBOjJp9ctpu/QSDcIsbAXs0h34nIIqTVLz+ehnCOw+pv6tbGgcccngSlH5kRVOO0zm/IEjmhAwu6rMHeq3ng6jWNHDpRIilvI+nJ5zOL7FNzrfP01KtF9zESwWp8gR4gu8pHo6H62m+ukgQDQk2Wt+t3dQAgklayMGufTnp8oSGsWBCO4t/r+P7U2y8LhpoyGO4UGBgDy4jKE0dwII2mFRVWTlgjw/iZFK4CXkeu89bNjrtZhVNwAE9tB5rsefP1p4sa5Mw1T3qpvp1CxzOslZ9I+BeGqI3E0aSe+XGSv1vniud5zehRk1kc75DZ5+xTORer7P1NlPB7pZIhB8nkL0ElwBxOQ="
  file: "whats-my-ip"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
